### ISSUE TITLE
访问localhost:555 是空白页面

### ISSUE THREAD

**Issue by 5dash** [hyboxu/evernote-markdown-win-theme#2]
![image](https://user-images.githubusercontent.com/53204626/64483564-b2b84b00-d236-11e9-9696-05d4e231f5e1.png)
将上图所有文件复制到`E:\soft\nginx-1.17.3\html`其中替换掉了原来的`index.html`，访问`localhost:555`显示空白页面

![image](https://user-images.githubusercontent.com/53204626/64483520-936cee00-d235-11e9-8596-a025496131c7.png)
替换`Evernote.exe`后

![image](https://user-images.githubusercontent.com/53204626/64483557-679e3800-d236-11e9-9b07-bb93ea5483b8.png)

版本号为
`6.18.8.718 (600718) Public (CE Build ce-62.1.8947, ME Build V1.0.28)`

**Comment by me1ting** [comment]
这是正常情况，由于我在新版本后添加了默认预览功能，而没有更新README，感谢提醒。
