### ISSUE TITLE
访问localhost:555 是空白页面， 修改Evernote.exe之后markdown加载不出来

### ISSUE THREAD

**Issue by table9** [hyboxu/evernote-markdown-win-theme#3]
您好，按照指示clone vue文件夹，执行``build.bat``文件，将编译得到的out文件夹中的文件拷贝到nginx文件加指定目录下并修改，但是随后访问``localhost:555`` 是空白页面，修改HEX码之后markdown也加载不出。我在Web服务器方面是个新手，没有按照指示安装依赖``npm install uglify-js``，可能问题就是出在这边。请问问题是出在构建编辑器这步么？PS：在Windows下我要怎么操作安装依赖这一步or编译好的在哪里可以下载？ Thanks for your attention.

**Comment by me1ting** [comment]
抱歉这几天忙其它事去了，回复晚了，见谅。

目前build只是单纯的压缩了一下js文件，你直接下载release就可以了。下载后按步骤操作就可以了，你应该是没有启动nginx吧。

**Comment by table9** [comment]
抱歉上周出差去了，按找步骤又试了一次，还是一样的问题打开evernote之后markdown的笔记无法加载。在任务管理器里面是能找到nginx.exe的进程的，应该不是没有启动nginx的问题。
Sorry to trouble you again.

**Comment by me1ting** [comment]
首先应该检查本地站点是否已经配置好了，你在启动nginx后，本机访问`http://localhost:555`，返回的是什么内容？双击是否显示一个markdown编辑页面，最好再用chrome的调试界面看一下，返回的是什么内容？
![Snipaste_2019-11-04_18-49-33](https://user-images.githubusercontent.com/52079867/68115786-2bd0d780-ff34-11e9-95e6-151cb2198836.png)

**Comment by table9** [comment]
您好，访问localhost:555 就是空白页面，console中显示
> main.min.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
Elements里面显示与index.html一致。请问是本地站点配置缺少什么么？

**Comment by me1ting** [comment]
本地站点只需要完成两个步骤：
1.复制编辑器文件到html文件下
2.修改conf/nginx.conf中的`listen       80;`为`listen       555;`

直接解压编辑器的所有文件到html中，而不应该包含额外的目录层次，你应该保证这样的文件结构：
```
html/
    fonts/
    vue/
    50x.html
    index.html
    main.min.css
    ...
```
祝你成功。

**Comment by table9** [comment]
Sorry, still I can't get the correct page on localhost:555. The portal in nginx.conf is 555, and the files under html dir look the same as you listed. I was wondering if it is possible to find the exact reason why it fails to load the main.min.js file.

**Comment by table9** [comment]
抱歉，我重试并检查了一下。但是 localhost:555 站点上的网页依然试空白页。conf/nginx.conf文件中的端口已经修改成了555，复制到html文件夹下的文件也没有额外路径。请问有办法能找到下面错误的具体原因么。
> main.min.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by me1ting** [comment]
提示没有找到`main.min.js`，你应该是直接将Git仓库的内容复制到了html里面吧。你应该从release里面下载我打包的editer.zip，复制解压的内容。

**Comment by table9** [comment]
好的谢谢，找到问题了，本地端口被禁用了。谢谢您的耐心解答！
